### ISSUE TITLE
issue(#1) 선택 사항

### ISSUE THREAD

**Issue by J-S-Kim** [17-1-SKKU-OSS/nerdcommenter#3]
```
context 1
//comment
context 2
```
C/C++의 파일 타입에서 위 와 같은 code가 존재할때
sexy comment 사용시
기존에는 *후에 space가 없어서 문제가 발생한다.

수정방안으로는 크게 2가지가 있을 수 있다.

1번
```
/*
 *context 1
 * //comment
 *context 2
 */
```
문제가 발생하는 부분만 띄어 써준다.

2번
```
/* 
 * context 1
 * //comment
 * context 2
 */
```
전부 띄어준다.

버그를 수정한다는 관점에서는 1번이 더 적절하고
sexy comment라는 기능의 의미를 생각해 보았을 때는 2번이 더 적절하다.

**Comment by J-S-Kim** [comment]
2번의 경우 
기본값이 0으로 set 되어있는 g:NERDSpaceDelims 변수를
1로 set하면 만들 수 있는 형태이기 때문에
**일단 1번의 경우로 수정하고 commit 함**

새로 수정하고 commit한 코드도 기존과 마찬가지로
g:NERDSpaceDelims을 1로 set한다면
2번의 모양처럼 만들 수 있음

**Comment by J-S-Kim** [comment]
추가로 떠오른 방식인데

```
/* 
 *context 1
 //comment
 *context 2
 */
```
그냥 이렇게도 괜찮을 것 같긴 하네요.
이걸 3번이라 하고
어떤게 가장 괜찮을까요?

**Comment by Skian12** [comment]
3번은 comment 지우는 기능 사용시 문제가 발생할 것 같습니다.
먼저 지우는 중에 버그가 발생할 가능성이 커보이고
이중 코멘트시 가장 바깥에 있는 주석만 지우는데 저렇게 하면 지우기 기능 사용시 모든 주석이 사라져서 사용자가 원치 않은 결과를 낳을 것 같습니다,

**Comment by Skian12** [comment]
확실히 버그 픽스 관점에선 1번이 괜찮아보이고, 보기에는 2번이 제일 보기 좋아보이네요.
그런데 띄어쓰기를 모든 라인에 넣으면 안되나요? 혹시나 NERDSpaceDelims을 건드릴 경우 다른 곳에서 문제.가 생기지 않을까 하는 염려가 듭니다.

**Comment by J-S-Kim** [comment]
2번처럼 띄어쓰기를 모든 라인에 넣어도 상관이 없긴 한데
그러한 모양을 사용자가 NERDSpaceDelims 값을 변경해 얼마든지 얻어낼 수 있어서
default는 1번 모양으로 만들어 놓고 선택의 폭을 넓혀 놓는것이 어떤가 생각했습니다.

(NERDSpaceDelims 변수 자체가 코드상에서만 변경할 수 있는 것이 아니라
사용자가 vimrc를 통해 변경할 수 있는 변수입니다.)

**Comment by Skian12** [comment]
혹시 변경법 알려주실 수 있나요?
만약에 변경후에 2번과 같은 모양이 나올 수 있는지 확인을 해봐야될 것 같습니다.

**Comment by J-S-Kim** [comment]
vimrc에 
`let g:NERDSpaceDelims = 1`
를 추가 하셔서 저장해도 되고

vi 실행하시고
`:let g:NERDSpaceDelims = 1`
엔터 입력하셔도 됩니다.

전자는 실행때마다 자동으로 적용되는 것이고 
후자는 실행때마다 해주셔야하는 것입니다.

**Comment by Skian12** [comment]
아 이것을 실행하면 Delimiters와 내용이 주어진 숫자만큼 띄어지게 되는군요
그런데 제가가진 버전에서는 1번 수정 내용이 없습니다.
혹시 1번 수정내용에서 SpaceDelims를 1로 두었을 때 내용들이 열맞춤이 되는지 확인 가능할까요?
