### ISSUE TITLE
[C]|NERDComEOLComment|  불편한점.

### ISSUE THREAD

**Issue by Skian12** [17-1-SKKU-OSS/nerdcommenter#5]
|NERDComEOLComment| 는 현재 라인 뒷부분을 주석처리 하는 기능인데,
단축키가 <leader>c$입니다. 그런데 $을 칠때 타임 딜레이가 꽤 생기는 편인데, 이 경우 앞에서 쳤던
<leader>키를 치지 않은것으로 판단하는 것 같습니다.
그래서 뒷부분이 아예 날라가고 삽입기능으로 들어갑니다.(c$만 치는 경우 이 기능이 활성화 됩니다.)

$가 아닌 다른 키를 사용한다면 좋을것 같은데(사용자에게 편리한 기능일수록 좋은 기능이니까요),
 위에서 말했듯이 c$기능과 관련된 단축키일 경우 때문에 섣불리 판단하긴 힘들어 보이네요

**Comment by J-S-Kim** [comment]
$ 키가 vim에서 커서를 현재라인의 가장 끝으로 옮기는 것으로
굉장히 자주 사용하고 있어서

현재 커서부터 현재 라인의 끝까지 주석처리를 하는 기능인 |NERDComEOLComment|의 단축키로
c$가 처음에는 불편할 수 있지만
직관적으로 봤을때 적합하다고 생각이듭니다.

**Comment by Skian12** [comment]
그러한 기능이라면 확실히 사용자 직관성 면에서 괜찮겠네요.
이 이슈는 닫겠습니다.
