### ISSUE TITLE
pull request 준비

### ISSUE THREAD

**Issue by J-S-Kim** [17-1-SKKU-OSS/nerdcommenter#6]
현재 제가 총 3번의 커밋을 했는데요
각 커밋에서의 코드 상황을
보기 좋게 간략화 하자면

원본 코드를 A라고하고 
그 외 대문자 알파벳을 추가된 코드라고 했을때

1. #3 issue number 1
A + B' + B

2. only //-style
A + B

3. n lines above the cursor
A + B + C

그래서 현재 최종적으로 3번과 같은 형태입니다.

앞으로 pull request를 위해서 아래와 같은 모양으로 브랜치를 2개 만든 후에 (명칭은 대략정한것)
(1) A + B (//-style bug fix)
(2) A + C (add n lines above the cursor)

2개를 각각 pull request해야 할 것 같습니다.

**Comment by Skian12** [comment]
잘 이해가 되지 않습니다.
어떤 상황에서 어떻게 변했는지 자세히 설명 부탁드려도 되겠습니까?

**Comment by Skian12** [comment]
1번 버그픽스
3번 위로 주석달기
인것 같은데 

2번은 어떤것인지 잘 모르겠습니다.

+ 현재 3번만 된건가요?

**Comment by J-S-Kim** [comment]
2번은 1번하고 동일한 버그를 픽스하는 것인데 B' 때문에 쓸데없는 것까지
변경이 되어서 그 부분 코드를 제거한 것입니다.

현재 3번인 상태인게
커밋을 1 -> 2 -> 3 순서대로 진행한 것입니다.
버그 픽스와 위로 주석달기가 같이 존재하는데
pull request를 할때는 두 개를 따로 분리 시켜서
(A + B + C) -> (A +B), (A + C)
각각 요청하는 것이 그 쪽에서도 결정하기 편할 것 같아서요

**Comment by Skian12** [comment]
그렇다면 혹시 2번상태 코드는 혹시 어떻게 보는지 알 수 있을까요?

**Comment by J-S-Kim** [comment]
```
git reset HEAD~1
git checkout -- plugin/NERD_commenter.vim
```
위와 같이하면 2번상태 코드로 돌아가고
(1대신에 다른 숫자를 넣으면 그 수만큼 돌아가겠다는 뜻입니다.)

`git pull`
하면 다시 원래 상태로 돌아옵니다.

**Comment by Skian12** [comment]
해당 방법은 local repository 내에서만 되는걸로 알고 있습니다.
(제가 reset 명령어를 치면 리셋 뒤에 스테이징하지 않은 변경 사항 :    이런식으로 오류메세지 뜹니다.)
아무래도 다른 방안을 찾아봐야될 것 같습니다.

**Comment by J-S-Kim** [comment]
아 넵 저도  reset 명령어 치면 그렇게 메세지가 나오는데
아마 그걸 스테이징하도록 만드는 명령어가 밑에있는
`git checkout -- plugin/NERD_commenter.vim`

이 명령어일거에요.
