### ISSUE TITLE
doc 수정 관련

### ISSUE THREAD

**Issue by J-S-Kim** [17-1-SKKU-OSS/nerdcommenter#7]
생각해보니 bug fix는 딱히 상관이 없는데

위로 주석을 다는 기능 같은 경우는
다른 command들과 마찬가지로
doc에 있는 txt파일에 기능과 command 설명을 추가해야 할 것 같습니다.

README.md까지 수정 해야하는지는 잘 모르겠습니다.

**Comment by Skian12** [comment]
이 부분에 대해서는 내일 만나서 이야기 또는 작성 하는게 나을것 같습니다.
